Convert all types to work with a PKI directory structure
The easy-rsa interface and file locations have historically been in constant
change. Currently, it looks like the project is steering towards having a single
PKI directory and keeping CAs, key pairs and configuration within it.

The packaging in distributions hasn't caught up everywhere (e.g. Debian still
ships a make-cadir helper) or OpenWrt for some reason has a global
/etc/easy-rsa/vars.

Supporting different versions and packaging in this set would be a nightmere,
thus this commit tries to do update the __easy_rsa_* types to create and work
with a simple PKI directory structure as "suggested" by upstream.

Yes, this is a breaking change and no efforts were made to allow for a
transition between the old and new style.

diff --git a/type/__easy_rsa_ca/gencode-remote b/type/__easy_rsa_ca/gencode-remote
--- a/type/__easy_rsa_ca/gencode-remote
+++ b/type/__easy_rsa_ca/gencode-remote
@@ -1,7 +1,7 @@
 #!/bin/sh -e
 #
 # 2020 Marko Seric (marko.seric at ssrq-sds-fds.ch)
-# 2020-2021 Dennis Camera (dennis.camera at ssrq-sds-fds.ch)
+# 2020,2021,2023 Dennis Camera (dennis.camera at riiengineering.ch)
 # 2020 Beni Ruef (bernhard.ruef at ssrq-sds-fds.ch)
 #
 # This file is part of the skonfig set __easy_rsa.
@@ -20,12 +20,16 @@
 # along with this set. If not, see <http://www.gnu.org/licenses/>.
 #
 
-quote() { printf "'%s'" "$(printf '%s' "$*" | sed -e "s/'/'\\\\''/g")"; }
+quote() {
+	sed -e "s/'/'\\\\''/g" -e "1s/^/'/" -e "\$s/\$/'/" <<-EOF
+	$*
+	EOF
+}
 
 os=$(cat "${__global:?}/explorer/os")
 state_is=$(cat "${__object:?}/explorer/state")
 
-base_dir=$(cat "${__object:?}/parameter/dir")
+pki_dir=$(cat "${__object:?}/parameter/dir")
 
 ca_type=$(cat "${__object:?}/parameter/type")
 
@@ -38,8 +42,10 @@ fi
 
 case ${os}
 in
-	(devuan|debian) easyrsa_bin='./easyrsa' ;;
-	(*) easyrsa_bin='easyrsa' ;;
+	(devuan|debian)
+		easyrsa_bin='/usr/share/easy-rsa/easyrsa' ;;
+	(*)
+		easyrsa_bin='easyrsa' ;;
 esac
 
 case ${state_is}
@@ -49,7 +55,7 @@ in
 		;;
 	(expired)
 		printf 'The certificate authority "%s" is expired.\n' "${common_name}" >&2
-		printf 'Please delete (or move away) the directory "%s" so that a fresh CA can be generated.\n' "${base_dir}" >&2
+		printf 'Please delete (or move away) the directory "%s" so that a fresh CA can be generated.\n' "${pki_dir}" >&2
 		exit 1
 		;;
 	(no-pki)
@@ -58,11 +64,11 @@ in
 		#       explorers. Due to this, it could happen that the state explorer
 		#       executes before the PKI has been initialised.
 
-		# Before doing anything else, check if the pki directory is present.
+		# Before doing anything else, check if the --dir is present.
 		cat <<-EOF
-		test -d $(quote "${base_dir}/pki") || {
-			echo 'Could not find pki directory in ${base_dir}.' >&2
-			echo 'Please make sure that __easy_rsa_pki${base_dir} is run first.' >&2
+		test -d $(quote "${pki_dir:?}") || {
+			echo 'Could not find a PKI directory structure in ${pki_dir-?}.' >&2
+			echo 'Please make sure that __easy_rsa_pki${pki_dir-} is run first.' >&2
 			exit 1
 		}
 		EOF
@@ -82,7 +88,7 @@ do
 		opt_params="${opt_params} --${option}=$(quote "${value}")"
 	fi
 done <"${__type:?}/files/param_mapping.txt"
-unset param option
+unset -v param option
 
 
 cmd_opts=' nopass'
@@ -96,40 +102,39 @@ in
 			exit 1
 		fi
 		;;
-	(sub) cmd_opts="${cmd_opts-}${cmd_opts:+ }subca" ;;
+	(sub)
+		cmd_opts="${cmd_opts-} subca"
+		;;
 	(*)
 		printf 'Invalid --type: %s\n' "${ca_type}" >&2
 		exit 1
 		;;
 esac
 
-printf 'cd %s || exit 1\n' "$(quote "${base_dir}")"
 printf '%s --pki-dir=%s --vars=%s --req-cn=%s %s --batch build-ca%s\n' \
 	"${easyrsa_bin}" \
-	"$(quote "${base_dir}/pki")" \
-	"$(quote "${base_dir}/vars")" \
+	"$(quote "${pki_dir}")" \
+	"$(quote "${pki_dir}/vars")" \
 	"$(quote "${common_name}")" \
 	"${opt_params# }" \
 	"${cmd_opts}"
 
 if test "${ca_type}" = 'sub' -a -f "${__object:?}/parameter/auto-sign-with"
 then
-	parent_ca=$(cat "${__object:?}/parameter/auto-sign-with")
-	easyrsa_parent="${easyrsa_bin:?} --pki-dir=$(quote "${parent_ca}/pki") --vars=$(quote "${parent_ca}/vars") --batch"
+	parent_pki=$(cat "${__object:?}/parameter/auto-sign-with")
+	easyrsa_parent="${easyrsa_bin:?} --pki-dir=$(quote "${parent_pki:?}") --vars=$(quote "${parent_pki:?}/vars") --batch"
 
 	cat <<-EOF
 
 	# Sign sub CA
-	days=\$(set_var(){ export "\$1=\$2"; }; EASYRSA_CALLER=1 . $(quote "${base_dir:?}/vars"); echo "\${EASYRSA_CA_EXPIRE:-3650}")
+	days=\$(set_var(){ export "\$1=\$2"; }; EASYRSA_CALLER=1 . $(quote "${pki_dir:?}/vars"); echo "\${EASYRSA_CA_EXPIRE:-3650}")
 
 	set -e
 
-	cd $(quote "${parent_ca}")
-
-	${easyrsa_parent} import-req $(quote "${base_dir}/pki/reqs/ca.req") $(quote "${__object_id:?}") \\
+	${easyrsa_parent} import-req $(quote "${pki_dir:?}/reqs/ca.req") $(quote "${__object_id:?}") \\
 	&& ${easyrsa_parent} --days=\$((days)) sign-req ca $(quote "${__object_id:?}")
 
-	cat $(quote "${parent_ca}/pki/issued/${__object_id:?}.crt") >$(quote "${base_dir}/pki/ca.crt")
-	cat $(quote "${parent_ca}/pki/ca.crt") $(quote "${base_dir}/pki/ca.crt") >$(quote "${base_dir}/pki/chain.pem")
+	cat $(quote "${parent_pki:?}/issued/${__object_id:?}.crt") >$(quote "${pki_dir:?}/ca.crt")
+	cat $(quote "${parent_pki:?}/ca.crt") $(quote "${pki_dir:?}/ca.crt") >$(quote "${pki_dir:?}/chain.pem")
 	EOF
 fi
diff --git a/type/__easy_rsa_cert/gencode-remote b/type/__easy_rsa_cert/gencode-remote
--- a/type/__easy_rsa_cert/gencode-remote
+++ b/type/__easy_rsa_cert/gencode-remote
@@ -1,7 +1,7 @@
 #!/bin/sh -e
 #
 # 2020 Marko Seric (marko.seric at ssrq-sds-fds.ch)
-# 2020 Dennis Camera (dennis.camera at ssrq-sds-fds.ch)
+# 2020,2023 Dennis Camera (dennis.camera at riiengineering.ch)
 # 2020 Beni Ruef (bernhard.ruef at ssrq-sds-fds.ch)
 #
 # This file is part of the skonfig set __easy_rsa.
@@ -20,9 +20,13 @@
 # along with this set. If not, see <http://www.gnu.org/licenses/>.
 #
 
-quote() { printf "'%s'" "$(printf '%s' "$*" | sed -e "s/'/'\\\\''/g")"; }
+quote() {
+	sed -e "s/'/'\\\\''/g" -e "1s/^/'/" -e "\$s/\$/'/" <<-EOF
+	$*
+	EOF
+}
 
-base_dir=$(cat "${__object:?}/parameter/dir")
+pki_dir=$(cat "${__object:?}/parameter/dir")
 
 state_should=$(cat "${__object:?}/parameter/state")
 state_is=$(cat "${__object:?}/explorer/state")
@@ -36,9 +40,9 @@ then
 	# Before doing anything else, check if the pki directory has been
 	# initialised in the meantime if the explorer didn't find it.
 	cat <<-EOF
-	test -d $(quote "${base_dir}/pki") || {
-		echo 'Could not find pki directory in ${base_dir}.' >&2
-		echo 'Please make sure that __easy_rsa_pki${base_dir} is ran first.' >&2
+	test -d $(quote "${pki_dir:?}") || {
+		echo 'Could not find a PKI directory structure in ${pki_dir-?}.' >&2
+		echo 'Please make sure that __easy_rsa_pki${pki_dir-} is run first.' >&2
 		exit 1
 	}
 	EOF
diff --git a/type/__easy_rsa_dh/gencode-remote b/type/__easy_rsa_dh/gencode-remote
--- a/type/__easy_rsa_dh/gencode-remote
+++ b/type/__easy_rsa_dh/gencode-remote
@@ -1,6 +1,6 @@
 #!/bin/sh -e
 #
-# 2021 Dennis Camera (dennis.camera at ssrq-sds-fds.ch)
+# 2021,2023 Dennis Camera (dennis.camera at riiengineering.ch)
 #
 # This file is part of the skonfig set __easy_rsa.
 #
@@ -18,19 +18,25 @@
 # along with this set. If not, see <http://www.gnu.org/licenses/>.
 #
 
-quote() { printf "'%s'" "$(printf '%s' "$*" | sed -e "s/'/'\\\\''/g")"; }
+quote() {
+	sed -e "s/'/'\\\\''/g" -e "1s/^/'/" -e "\$s/\$/'/" <<-EOF
+	$*
+	EOF
+}
 
 os=$(cat "${__global:?}/explorer/os")
 
-base_dir=/${__object_id:?}
+pki_dir=/${__object_id:?}
 
 state_should=$(cat "${__object:?}/parameter/state")
 state_is=$(cat "${__object:?}/explorer/state")
 
 case ${os}
 in
-	(devuan|debian) easyrsa_bin='./easyrsa' ;;
-	(*) easyrsa_bin='easyrsa' ;;
+	(devuan|debian)
+		easyrsa_bin='/usr/share/easy-rsa/easyrsa' ;;
+	(*)
+		easyrsa_bin='easyrsa' ;;
 esac
 
 
@@ -49,9 +55,9 @@ then
 	# Before doing anything else, check if the pki directory has been
 	# initialised in the meantime if the explorer didn't find it.
 	cat <<-EOF
-	test -d $(quote "${base_dir}/pki") || {
-		echo 'Could not find pki directory in ${base_dir}.' >&2
-		echo 'Please make sure that __easy_rsa_pki${base_dir} is ran first.' >&2
+	test -d $(quote "${pki_dir:?}") || {
+		echo 'Could not find a PKI directory structure in ${pki_dir-?}.' >&2
+		echo 'Please make sure that __easy_rsa_pki${pki_dir-} is run first.' >&2
 		exit 1
 	}
 	EOF
@@ -61,13 +67,11 @@ then
 	state_is='absent'
 fi
 
-easyrsa_base_cmd="${easyrsa_bin} --pki-dir=$(quote "${base_dir:?}/pki") --vars=$(quote "${base_dir:?}/vars") --batch"
+easyrsa_base_cmd="${easyrsa_bin} --pki-dir=$(quote "${pki_dir:?}") --vars=$(quote "${pki_dir:?}/vars") --batch"
 
 case ${state_should}
 in
 	(present)
-		printf 'cd %s || exit 1\n' "$(quote "${base_dir:?}")"
-
 		output_redir='>/dev/null'
 		if test -f "${__object:?}/parameter/background"
 		then
@@ -78,7 +82,7 @@ in
 		printf '%s gen-dh %s\n' "${easyrsa_base_cmd}" "${output_redir}"
 		;;
 	(absent)
-		printf 'rm -f %s\n' "$(quote "${base_dir}/pki/dh.pem")"
+		printf 'rm -f %s\n' "$(quote "${pki_dir:?}/dh.pem")"
 		;;
 	(*)
 		printf 'Invalid --state: %s\n' "${state_should}" >&2
diff --git a/type/__easy_rsa_pki/gencode-remote b/type/__easy_rsa_pki/gencode-remote
--- a/type/__easy_rsa_pki/gencode-remote
+++ b/type/__easy_rsa_pki/gencode-remote
@@ -1,7 +1,7 @@
 #!/bin/sh -e
 #
-# 2020 Marko Seric (marko.seric@ssrq-sds-fds.ch)
-# 2020-2021 Dennis Camera (dennis camera at ssrq-sds-fds.ch)
+# 2020 Marko Seric (marko.seric at ssrq-sds-fds.ch)
+# 2020,2021,2023 Dennis Camera (dennis camera at riiengineering.ch)
 #
 # This file is part of the skonfig set __easy_rsa.
 #
@@ -19,7 +19,11 @@
 # along with this set. If not, see <http://www.gnu.org/licenses/>.
 #
 
-quote() { printf "'%s'" "$(printf '%s' "$*" | sed -e "s/'/'\\\\''/g")"; }
+quote() {
+	sed -e "s/'/'\\\\''/g" -e "1s/^/'/" -e "\$s/\$/'/" <<-EOF
+	$*
+	EOF
+}
 drop_awk_comments() { quote "$(sed '/^[[:blank:]]*#.*$/d;/^$/d' "$@")"; }
 quote_nonnum() { sed 's/^.*[^0-9].*$/"&"/;q' "$@"; }
 
@@ -28,55 +32,41 @@ os=$(cat "${__global:?}/explorer/os")
 
 state_is=$(cat "${__object:?}/explorer/state")
 
-base_dir="/${__object_id:?}"
-vars_file="${base_dir}/vars"
+pki_dir="/${__object_id:?}"
+vars_file="${pki_dir:?}/vars"
 
 if test "${state_is}" = 'suspicious'
 then
-	printf "Directory %s exists, but doesn't look like a valid PKI.\n" "${base_dir}" >&2
+	printf "Directory %s exists, but doesn't look like a valid PKI.\n" "${pki_dir-}" >&2
 	printf 'Please clean it up manually and try again.\n'
 	exit 1
 fi
 
 
+case ${os}
+in
+	(debian|devuan)
+		easyrsa_bin='/usr/share/easy-rsa/easyrsa'
+		;;
+	(openwrt)
+		easyrsa_bin='easyrsa'
+		;;
+	(*)
+		exit 1  # fail, OS whitelist should be in manifest
+		;;
+esac
+
+
 ################################################################################
-# Create base directory structure
+# Create PKI directory structure
 
-if test "${state_is}" = 'absent'
-then
-	case ${os}
-	in
-		(debian|devuan)
-			easyrsa_bin='./easyrsa'
-
-			# Create base directory structure using Debian's make-cadir(1)
-			printf 'make-cadir %s\n' "$(quote "${base_dir}")"
-			;;
-		(openwrt)
-			easyrsa_bin='easyrsa'
-
-			# Create base directory structure
-			printf 'test -d %s || mkdir %s\n' \
-				"$(quote "${base_dir}")" "$(quote "${base_dir}")"
-
-			for _file in vars openssl-easyrsa.cnf
-			do
-				# NOTE: /usr/lib/easy-rsa/* actually links into /etc/easy-rsa
-				printf 'cat %s >%s\n' \
-					"$(quote "/usr/lib/easy-rsa/${_file}")" \
-					"$(quote "${base_dir}/${_file}")"
-			done
-			unset _file
-
-			printf 'ln -s %s %s\n' \
-				"$(quote "/usr/lib/easy-rsa/x509-types")" \
-				"$(quote "${base_dir}/x509-types")"
-			;;
-		(*)
-			exit 1  # fail, OS whitelist should be in manifest
-			;;
-	esac
-fi
+case ${state_is}
+in
+	(absent)
+		printf '%s --batch --pki-dir=%s init-pki\n' \
+			"${easyrsa_bin}" "$(quote "${pki_dir:?}")"
+		;;
+esac
 
 
 ################################################################################
@@ -104,15 +94,4 @@ ${vars_and_values}
 EOF
 rm -f $(quote "${vars_file}.tmp")
 CODE
-fi
-
-
-################################################################################
-# Init PKI subdirectory
-
-if test "${state_is}" = 'absent'
-then
-	# NOTE: init-pki creates a pki subfolder in the current working directory!
-	printf 'cd %s || exit 1\n' "$(quote "${base_dir}")"
-	printf '%s --batch init-pki\n' "${easyrsa_bin}"
 fi
